spring.application.name=stockmaster-backend
server.port=${PORT:8080}

spring.profiles.active=supabase

# JWT Config
app.jwt.secret=zZO8A8hT3U4ZSL+uQOPGkGKpUQ/CMcAEzBcHWKmWYZNyzwkNDQAfq3GzyAW7cm21WnDxHpZAV83x8tSt9CY/Mw==
app.jwt.expiration-ms=86400000

# Formato fecha
spring.jackson.date-format=yyyy-MM-dd'T'HH:mm:ss
spring.jackson.time-zone=America/Lima
