# Conexion Supabase Produccion
spring.datasource.url=jdbc:postgresql://aws-0-us-west-2.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
spring.datasource.username=postgres.wgxyrjavgwzebjvajqes
spring.datasource.password=7vY4rJZ1UA9V1wkg
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Clave JWT Supabase
app.jwt.secret=zZO8A8hT3U4ZSL+uQOPGkGKpUQ/CMcAEzBcHWKmWYZNyzwkNDQAfq3GzyAW7cm21WnDxHpZAV83x8tSt9CY/Mw==
app.jwt.expiration-ms=86400000
